<?php
$xmlString = <<<EOD
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <Cork_INBOUND>
        <protectParams>
            <serviceId>25549</serviceId>
            <destination>00353214944694</destination>
        </protectParams>
    </Cork_INBOUND>
    <SheffieldArcherRoad_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01142367823</destination>
        </protectParams>
    </SheffieldArcherRoad_INBOUND>
    <NottinghamGiltbrook_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01159387330</destination>
        </protectParams>
    </NottinghamGiltbrook_INBOUND>
    <NottinghamCastleBoulevard_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01159484104</destination>
        </protectParams>
    </NottinghamCastleBoulevard_INBOUND>
    <BristolBroadmead_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01179456170</destination>
        </protectParams>
    </BristolBroadmead_INBOUND>
    <BristolEastgate_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01179526100</destination>
        </protectParams>
    </BristolEastgate_INBOUND>
    <Reading_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01189205110</destination>
        </protectParams>
    </Reading_INBOUND>
    <Poole_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01202545680</destination>
        </protectParams>
    </Poole_INBOUND>
    <Bolton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01204668310</destination>
        </protectParams>
    </Bolton_INBOUND>
    <Colchester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01206711290</destination>
        </protectParams>
    </Colchester_INBOUND>
    <SuttonColdfield_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01213215920</destination>
        </protectParams>
    </SuttonColdfield_INBOUND>
    <BirminghamQuinton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01215066890</destination>
        </protectParams>
    </BirminghamQuinton_INBOUND>
    <BirminghamPavillions_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01215066890</destination>
        </protectParams>
    </BirminghamPavillions_INBOUND>
    <Solihull_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01217043573</destination>
        </protectParams>
    </Solihull_INBOUND>
    <Cambridge_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01223345620</destination>
        </protectParams>
    </Cambridge_INBOUND>
    <Aberdeen_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01224621701</destination>
        </protectParams>
    </Aberdeen_INBOUND>
    <Bath_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01225471222</destination>
        </protectParams>
    </Bath_INBOUND>
    <Canterbury_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01227479222</destination>
        </protectParams>
    </Canterbury_INBOUND>
    <CanterburyGiftsAndAccessories_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01227787155</destination>
        </protectParams>
    </CanterburyGiftsAndAccessories_INBOUND>
    <CarlisleLondonRoad_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01228635840</destination>
        </protectParams>
    </CarlisleLondonRoad_INBOUND>
    <Bedford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01908528130</destination>
        </protectParams>
    </Bedford_INBOUND>
    <Cheltenham_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01242225590</destination>
        </protectParams>
    </Cheltenham_INBOUND>
    <Chichester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01243520900</destination>
        </protectParams>
    </Chichester_INBOUND>
    <Chichester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01243779646</destination>
        </protectParams>
    </Chichester_INBOUND>
    <Chester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01244400966</destination>
        </protectParams>
    </Chester_INBOUND>
    <Chelmsford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01245213230</destination>
        </protectParams>
    </Chelmsford_INBOUND>
    <Chesterfield_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01246575650</destination>
        </protectParams>
    </Chesterfield_INBOUND>
    <BangorCaernarfonRoad_INBOUND>
        <protectParams>
            <serviceId>25549</serviceId>
            <destination>01248354663</destination>
        </protectParams>
    </BangorCaernarfonRoad_INBOUND>
    <Chippenham_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01249454700</destination>
        </protectParams>
    </Chippenham_INBOUND>
    <Farnham_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01252719861</destination>
        </protectParams>
    </Farnham_INBOUND>
    <FarnhamHawthornHouse_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01252741760</destination>
        </protectParams>
    </FarnhamHawthornHouse_INBOUND>
    <Basingstoke_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01256859970</destination>
        </protectParams>
    </Basingstoke_INBOUND>
    <Congleton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01260270516</destination>
        </protectParams>
    </Congleton_INBOUND>
    <Carmarthen_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01267221093</destination>
        </protectParams>
    </Carmarthen_INBOUND>
    <Basildon_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01268247360</destination>
        </protectParams>
    </Basildon_INBOUND>
    <Rayleigh_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01268741459</destination>
        </protectParams>
    </Rayleigh_INBOUND>
    <Crewe_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01270504820</destination>
        </protectParams>
    </Crewe_INBOUND>
    <Nantwich_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01270619865</destination>
        </protectParams>
    </Nantwich_INBOUND>
    <Barnstaple_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01271859710</destination>
        </protectParams>
    </Barnstaple_INBOUND>
    <Lewes_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01273476936</destination>
        </protectParams>
    </Lewes_INBOUND>
    <Shipley_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01274714720</destination>
        </protectParams>
    </Shipley_INBOUND>
    <Camberley_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01276414620</destination>
        </protectParams>
    </Camberley_INBOUND>
    <Brentwood_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01277200776</destination>
        </protectParams>
    </Brentwood_INBOUND>
    <Harlow_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01279410008</destination>
        </protectParams>
    </Harlow_INBOUND>
    <BuryStEdmunds_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01284764169</destination>
        </protectParams>
    </BuryStEdmunds_INBOUND>
    <Cirencester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01285656108</destination>
        </protectParams>
    </Cirencester_INBOUND>
    <Crawley_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01293539114</destination>
        </protectParams>
    </Crawley_INBOUND>
    <Dorchester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01305211820</destination>
        </protectParams>
    </Dorchester_INBOUND>
    <EdinburghGeorgeStreet_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01312200110</destination>
        </protectParams>
    </EdinburghGeorgeStreet_INBOUND>
    <EdinburghStraiton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01314407370</destination>
        </protectParams>
    </EdinburghStraiton_INBOUND>
    <Eastbourne_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01323737319</destination>
        </protectParams>
    </Eastbourne_INBOUND>
    <Darlington_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01325734110</destination>
        </protectParams>
    </Darlington_INBOUND>
    <Dudley_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01384471690</destination>
        </protectParams>
    </Dudley_INBOUND>
    <Dumfries_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01387242480</destination>
        </protectParams>
    </Dumfries_INBOUND>
    <Exeter_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01392430173</destination>
        </protectParams>
    </Exeter_INBOUND>
    <Woodbridge_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01394389110</destination>
        </protectParams>
    </Woodbridge_INBOUND>
    <Horsham_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01403276741</destination>
        </protectParams>
    </Horsham_INBOUND>
    <Glasgow_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01413311673</destination>
        </protectParams>
    </Glasgow_INBOUND>
    <GlasgowBraehead_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01418861635</destination>
        </protectParams>
    </GlasgowBraehead_INBOUND>
    <Harrogate_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01423507402</destination>
        </protectParams>
    </Harrogate_INBOUND>
    <Gainsborough_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01427619010</destination>
        </protectParams>
    </Gainsborough_INBOUND>
    <Hereford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01432371140</destination>
        </protectParams>
    </Hereford_INBOUND>
    <Haverfordwest_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01437771930</destination>
        </protectParams>
    </Haverfordwest_INBOUND>
    <Stevenage_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01438842470</destination>
        </protectParams>
    </Stevenage_INBOUND>
    <HemelHempstead_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01442220960</destination>
        </protectParams>
    </HemelHempstead_INBOUND>
    <Berkhamsted_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01442870457</destination>
        </protectParams>
    </Berkhamsted_INBOUND>
    <HaywardsHeath_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01444884790</destination>
        </protectParams>
    </HaywardsHeath_INBOUND>
    <Gloucester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01452725961</destination>
        </protectParams>
    </Gloucester_INBOUND>
    <Inverness_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01463224122</destination>
        </protectParams>
    </Inverness_INBOUND>
    <Ipswich_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01473639254</destination>
        </protectParams>
    </Ipswich_INBOUND>
    <Grantham_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01476512970</destination>
        </protectParams>
    </Grantham_INBOUND>
    <Hull_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01482221422</destination>
        </protectParams>
    </Hull_INBOUND>
    <Beverley_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01482864685</destination>
        </protectParams>
    </Beverley_INBOUND>
    <Guildford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01483510930</destination>
        </protectParams>
    </Guildford_INBOUND>
    <Huddersfield_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01484532795</destination>
        </protectParams>
    </Huddersfield_INBOUND>
    <Henley-on-Thames_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01491570810</destination>
        </protectParams>
    </Henley-on-Thames_INBOUND>
    <Llandudno_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01492869180</destination>
        </protectParams>
    </Llandudno_INBOUND>
    <Amersham_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01494733850</destination>
        </protectParams>
    </Amersham_INBOUND>
    <Beccles_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01502719330</destination>
        </protectParams>
    </Beccles_INBOUND>
    <Liverpool_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01515302100</destination>
        </protectParams>
    </Liverpool_INBOUND>
    <Speke_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01517285870</destination>
        </protectParams>
    </Speke_INBOUND>
    <Lincoln_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01522510027</destination>
        </protectParams>
    </Lincoln_INBOUND>
    <Lancaster_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01524591900</destination>
        </protectParams>
    </Lancaster_INBOUND>
    <Kettering_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01536527160</destination>
        </protectParams>
    </Kettering_INBOUND>
    <WindermereGiftsAndAccessories_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01539447050</destination>
        </protectParams>
    </WindermereGiftsAndAccessories_INBOUND>
    <Kendal_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01539741173</destination>
        </protectParams>
    </Kendal_INBOUND>
    <Knutsford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01565755691</destination>
        </protectParams>
    </Knutsford_INBOUND>
    <Tenterden_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01580765821</destination>
        </protectParams>
    </Tenterden_INBOUND>
    <Dunstable_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01582470120</destination>
        </protectParams>
    </Dunstable_INBOUND>
    <NorwichEaton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01603505041</destination>
        </protectParams>
    </NorwichEaton_INBOUND>
    <Norwich_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01603677630</destination>
        </protectParams>
    </Norwich_INBOUND>
    <NorthamptonMLStJames_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01604609910</destination>
        </protectParams>
    </NorthamptonMLStJames_INBOUND>
    <Northallerton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01609781874</destination>
        </protectParams>
    </Northallerton_INBOUND>
    <ManchesterBartonSquare_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01617492610</destination>
        </protectParams>
    </ManchesterBartonSquare_INBOUND>
    <Maidstone_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01622358740</destination>
        </protectParams>
    </Maidstone_INBOUND>
    <Mansfield_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01623412820</destination>
        </protectParams>
    </Mansfield_INBOUND>
    <Wilmslow_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01625446100</destination>
        </protectParams>
    </Wilmslow_INBOUND>
    <Newbury_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01635234060</destination>
        </protectParams>
    </Newbury_INBOUND>
    <Stockton-on-Tees_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01642702280</destination>
        </protectParams>
    </Stockton-on-Tees_INBOUND>
    <Morpeth_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01670500750</destination>
        </protectParams>
    </Morpeth_INBOUND>
    <Marlborough_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01672513176</destination>
        </protectParams>
    </Marlborough_INBOUND>
    <NewtownCL_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01686614716</destination>
        </protectParams>
    </NewtownCL_INBOUND>
    <Orpington_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01689821188</destination>
        </protectParams>
    </Orpington_INBOUND>
    <Birkdale_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01704566025</destination>
        </protectParams>
    </Birkdale_INBOUND>
    <Salisbury_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01722343820</destination>
        </protectParams>
    </Salisbury_INBOUND>
    <Petersfield_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01730268387</destination>
        </protectParams>
    </Petersfield_INBOUND>
    <Sevenoaks_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01732779070</destination>
        </protectParams>
    </Sevenoaks_INBOUND>
    <PeterboroughBretton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01733373150</destination>
        </protectParams>
    </PeterboroughBretton_INBOUND>
    <Reigate_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01737230190</destination>
        </protectParams>
    </Reigate_INBOUND>
    <Shrewsbury_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01743246856</destination>
        </protectParams>
    </Shrewsbury_INBOUND>
    <SheptonMallet_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01749340350</destination>
        </protectParams>
    </SheptonMallet_INBOUND>
    <Plymouth_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01752251271</destination>
        </protectParams>
    </Plymouth_INBOUND>
    <PlymouthConcession_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01752260018</destination>
        </protectParams>
    </PlymouthConcession_INBOUND>
    <Windsor_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01753829950</destination>
        </protectParams>
    </Windsor_INBOUND>
    <Skipton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01756799630</destination>
        </protectParams>
    </Skipton_INBOUND>
    <Biggleswade_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01767310800</destination>
        </protectParams>
    </Biggleswade_INBOUND>
    <Preston_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01772888051</destination>
        </protectParams>
    </Preston_INBOUND>
    <NewcastleUnderLyme_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01782715184</destination>
        </protectParams>
    </NewcastleUnderLyme_INBOUND>
    <Staines_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01784415420</destination>
        </protectParams>
    </Staines_INBOUND>
    <Stafford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01785221850</destination>
        </protectParams>
    </Stafford_INBOUND>
    <Stirling_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01786472430</destination>
        </protectParams>
    </Stirling_INBOUND>
    <Rugby_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01788554420</destination>
        </protectParams>
    </Rugby_INBOUND>
    <Stratford-Upon-Avon_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01789403970</destination>
        </protectParams>
    </Stratford-Upon-Avon_INBOUND>
    <Swansea_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01792560380</destination>
        </protectParams>
    </Swansea_INBOUND>
    <Swindon_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01793429930</destination>
        </protectParams>
    </Swindon_INBOUND>
    <SaffronWalden_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01799512280</destination>
        </protectParams>
    </SaffronWalden_INBOUND>
    <Taunton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01823345940</destination>
        </protectParams>
    </Taunton_INBOUND>
    <Broadstairs_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01843874190</destination>
        </protectParams>
    </Broadstairs_INBOUND>
    <Oxford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01865553787</destination>
        </protectParams>
    </Oxford_INBOUND>
    <Bicester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01869366560</destination>
        </protectParams>
    </Bicester_INBOUND>
    <Truro_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01872226830</destination>
        </protectParams>
    </Truro_INBOUND>
    <TunbridgeWells_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01892546702</destination>
        </protectParams>
    </TunbridgeWells_INBOUND>
    <Workington_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01900734480</destination>
        </protectParams>
    </Workington_INBOUND>
    <Wolverhampton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01902723720</destination>
        </protectParams>
    </Wolverhampton_INBOUND>
    <WorthingHome_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01903218456</destination>
        </protectParams>
    </WorthingHome_INBOUND>
    <YorkMonksCross_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01904686930</destination>
        </protectParams>
    </YorkMonksCross_INBOUND>
    <Worcester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01905734634</destination>
        </protectParams>
    </Worcester_INBOUND>
    <MiltonKeynes_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01908528130</destination>
        </protectParams>
    </MiltonKeynes_INBOUND>
    <Durham_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01913751210</destination>
        </protectParams>
    </Durham_INBOUND>
    <Gateshead_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01914618730</destination>
        </protectParams>
    </Gateshead_INBOUND>
    <Wakefield_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01924203360</destination>
        </protectParams>
    </Wakefield_INBOUND>
    <Warrington_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01925236150</destination>
        </protectParams>
    </Warrington_INBOUND>
    <LeamingtonSpa_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01926831689</destination>
        </protectParams>
    </LeamingtonSpa_INBOUND>
    <Weybridge_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01932839942</destination>
        </protectParams>
    </Weybridge_INBOUND>
    <Yeovil_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01935420102</destination>
        </protectParams>
    </Yeovil_INBOUND>
    <Ilkley_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01943885140</destination>
        </protectParams>
    </Ilkley_INBOUND>
    <Telford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01952219930</destination>
        </protectParams>
    </Telford_INBOUND>
    <Winchester_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01962873560</destination>
        </protectParams>
    </Winchester_INBOUND>
    <NewportIOW_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01983559031</destination>
        </protectParams>
    </NewportIOW_INBOUND>
    <HarrietStreet_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02078387480</destination>
        </protectParams>
    </HarrietStreet_INBOUND>
    <Bromley_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02082909360</destination>
        </protectParams>
    </Bromley_INBOUND>
    <StaplesCorner_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02084382420</destination>
        </protectParams>
    </StaplesCorner_INBOUND>
    <SouthWoodford_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02085308718</destination>
        </protectParams>
    </SouthWoodford_INBOUND>
    <Kingston_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02085466592</destination>
        </protectParams>
    </Kingston_INBOUND>
    <Purley_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02086603579</destination>
        </protectParams>
    </Purley_INBOUND>
    <LondonWestfield_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02087354060</destination>
        </protectParams>
    </LondonWestfield_INBOUND>
    <Putney_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02087892319</destination>
        </protectParams>
    </Putney_INBOUND>
    <Southampton_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02380682720</destination>
        </protectParams>
    </Southampton_INBOUND>
    <Southsea_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02392731573</destination>
        </protectParams>
    </Southsea_INBOUND>
    <Coleraine_INBOUND>
        <protectParams>
            <serviceId>25549</serviceId>
            <destination>02870353735</destination>
        </protectParams>
    </Coleraine_INBOUND>
    <Omagh_INBOUND>
        <protectParams>
            <serviceId>25549</serviceId>
            <destination>02882251291</destination>
        </protectParams>
    </Omagh_INBOUND>
    <Belfast_INBOUND>
        <protectParams>
            <serviceId>25549</serviceId>
            <destination>02890436420</destination>
        </protectParams>
    </Belfast_INBOUND>
    <BelfastBoucherRoad_INBOUND>
        <protectParams>
            <serviceId>25549</serviceId>
            <destination>02890687454</destination>
        </protectParams>
    </BelfastBoucherRoad_INBOUND>
    <BangorBloomfieldPark_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02891475760</destination>
        </protectParams>
    </BangorBloomfieldPark_INBOUND>
    <Cardiff_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02920348820</destination>
        </protectParams>
    </Cardiff_INBOUND>
    <CardiffTy-Glas_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02920741080</destination>
        </protectParams>
    </CardiffTy-Glas_INBOUND>
    <MeadowhallMLReloc_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01142516910</destination>
        </protectParams>
    </MeadowhallMLReloc_INBOUND>
    <ChesterCenturianPoint_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01244394790</destination>
        </protectParams>
    </ChesterCenturianPoint_INBOUND>
    <EbayWestHallam_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>01686614710</destination>
        </protectParams>
    </EbayWestHallam_INBOUND>
    <Havant_INBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <destination>02392456520</destination>
        </protectParams>
    </Havant_INBOUND>
    <Scenario_INBOUND_POST>
        <protectParams>
            <destination>01686620399</destination>
        </protectParams>
    </Scenario_INBOUND_POST>
    <Scenario_INBOUND_CS>
        <protectParams>
            <destination>01686620301</destination>
        </protectParams>
    </Scenario_INBOUND_CS>
    <Scenario_INBOUND_DESIGN>
        <protectParams>
            <destination>01686620397</destination>
        </protectParams>
    </Scenario_INBOUND_DESIGN>
    <Scenario_INBOUND_PHL>
        <protectParams>
            <destination>01686620717</destination>
        </protectParams>
    </Scenario_INBOUND_PHL>
    <Scenario_INBOUND_ADM>
        <protectParams>
            <destination>01686620580</destination>
        </protectParams>
    </Scenario_INBOUND_ADM>
    <Scenario_INBOUND_AE>
        <protectParams>
            <destination>01686620581</destination>
        </protectParams>
    </Scenario_INBOUND_AE>
    <Scenario_INBOUND_HP>
        <protectParams>
            <destination>01686620582</destination>
        </protectParams>
    </Scenario_INBOUND_HP>
    <Scenario_INBOUND_JL>
        <protectParams>
            <destination>01686620583</destination>
        </protectParams>
    </Scenario_INBOUND_JL>
    <Scenario_INBOUND_JW>
        <protectParams>
            <destination>01686620584</destination>
        </protectParams>
    </Scenario_INBOUND_JW>
    <Scenario_INBOUND_LM>
        <protectParams>
            <destination>01686620585</destination>
        </protectParams>
    </Scenario_INBOUND_LM>
    <Scenario_INBOUND_NS>
        <protectParams>
            <destination>01686620586</destination>
        </protectParams>
    </Scenario_INBOUND_NS>
    <Scenario_INBOUND_RB>
        <protectParams>
            <destination>01686620587</destination>
        </protectParams>
    </Scenario_INBOUND_RB>
    <Scenario_INBOUND_RM>
        <protectParams>
            <destination>01686620588</destination>
        </protectParams>
    </Scenario_INBOUND_RM>
    <Scenario_INBOUND_SH>
        <protectParams>
            <destination>01686620589</destination>
        </protectParams>
    </Scenario_INBOUND_SH>
    <Scenario_INBOUND_HR>
        <protectParams>
            <destination>01686620590</destination>
        </protectParams>
    </Scenario_INBOUND_HR>
    <Scenario_INBOUND_MW>
        <protectParams>
            <destination>01686620591</destination>
        </protectParams>
    </Scenario_INBOUND_MW>
    <Scenario_INBOUND_TR>
        <protectParams>
            <destination>01686620592</destination>
        </protectParams>
    </Scenario_INBOUND_TR>
    <Scenario_INBOUND_REC>
        <protectParams>
            <destination>01686620594</destination>
        </protectParams>
    </Scenario_INBOUND_REC>
    <Scenario_INBOUND_JV>
        <protectParams>
            <destination>01686620595</destination>
        </protectParams>
    </Scenario_INBOUND_JV>
    <Scenario_INBOUND_LJ>
        <protectParams>
            <destination>01686620596</destination>
        </protectParams>
    </Scenario_INBOUND_LJ>
    <Scenario_INBOUND_NJ>
        <protectParams>
            <destination>01686620597</destination>
        </protectParams>
    </Scenario_INBOUND_NJ>
    <Scenario_INBOUND_RA>
        <protectParams>
            <destination>01686620598</destination>
        </protectParams>
    </Scenario_INBOUND_RA>
    <Scenario_INBOUND_ST>
        <protectParams>
            <destination>01686620599</destination>
        </protectParams>
    </Scenario_INBOUND_ST>
    <Scenario_INBOUND_1>
        <protectParams>
            <destination>01686620580</destination>
        </protectParams>
    </Scenario_INBOUND_1>
    <Scenario_INBOUND_2>
        <protectParams>
            <destination>01686620581</destination>
        </protectParams>
    </Scenario_INBOUND_2>
    <Scenario_INBOUND_3>
        <protectParams>
            <destination>01686620582</destination>
        </protectParams>
    </Scenario_INBOUND_3>
    <Scenario_INBOUND_4>
        <protectParams>
            <destination>01686620583</destination>
        </protectParams>
    </Scenario_INBOUND_4>
    <Scenario_INBOUND_5>
        <protectParams>
            <destination>01686620584</destination>
        </protectParams>
    </Scenario_INBOUND_5>
    <Scenario_INBOUND_6>
        <protectParams>
            <destination>01686620585</destination>
        </protectParams>
    </Scenario_INBOUND_6>
    <Scenario_INBOUND_7>
        <protectParams>
            <destination>01686620586</destination>
        </protectParams>
    </Scenario_INBOUND_7>
    <Scenario_INBOUND_8>
        <protectParams>
            <destination>01686620587</destination>
        </protectParams>
    </Scenario_INBOUND_8>
    <Scenario_INBOUND_9>
        <protectParams>
            <destination>01686620588</destination>
        </protectParams>
    </Scenario_INBOUND_9>
    <Scenario_INBOUND_10>
        <protectParams>
            <destination>01686620589</destination>
        </protectParams>
    </Scenario_INBOUND_10>
    <Scenario_INBOUND_11>
        <protectParams>
            <destination>01686620590</destination>
        </protectParams>
    </Scenario_INBOUND_11>
    <Scenario_INBOUND_12>
        <protectParams>
            <destination>01686620591</destination>
        </protectParams>
    </Scenario_INBOUND_12>
    <Scenario_INBOUND_13>
        <protectParams>
            <destination>01686620592</destination>
        </protectParams>
    </Scenario_INBOUND_13>
    <Scenario_INBOUND_14>
        <protectParams>
            <destination>01686620594</destination>
        </protectParams>
    </Scenario_INBOUND_14>
    <Scenario_INBOUND_15>
        <protectParams>
            <destination>01686620595</destination>
        </protectParams>
    </Scenario_INBOUND_15>
    <Scenario_INBOUND_16>
        <protectParams>
            <destination>01686620596</destination>
        </protectParams>
    </Scenario_INBOUND_16>
    <Scenario_INBOUND_17>
        <protectParams>
            <destination>01686620597</destination>
        </protectParams>
    </Scenario_INBOUND_17>
    <Scenario_INBOUND_18>
        <protectParams>
            <destination>01686620598</destination>
        </protectParams>
    </Scenario_INBOUND_18>
    <Scenario_INBOUND_19>
        <protectParams>
            <destination>01686620599</destination>
        </protectParams>
    </Scenario_INBOUND_19>
    <Scenario_OUTBOUND>
        <protectParams>
            <serviceId>25139</serviceId>
            <outboundCli>03332008009</outboundCli>
            <scenario/>
            <callSetup>outbound</callSetup>
            <whisperOnDemand>1</whisperOnDemand>
            <alwaysSuppress>1</alwaysSuppress>
            <enableSpeech>0</enableSpeech>
            <whisperSetup>phoneToScreen</whisperSetup>
        </protectParams>
    </Scenario_OUTBOUND>
    <Scenario_STORES_OUTBOUND>
        <protectParams>
            <serviceId>25537</serviceId>
            <outboundCli>03332008009</outboundCli>
            <scenario/>
            <callSetup>outbound</callSetup>
            <whisperOnDemand>1</whisperOnDemand>
            <alwaysSuppress>1</alwaysSuppress>
            <enableSpeech>0</enableSpeech>
            <whisperSetup>phoneToScreen</whisperSetup>
        </protectParams>
    </Scenario_STORES_OUTBOUND>
    <Scenario_STORES_EUR_OUTBOUND>
        <protectParams>
            <serviceId>25549</serviceId>
            <outboundCli>03332008009</outboundCli>
            <scenario/>
            <callSetup>outbound</callSetup>
            <whisperOnDemand>1</whisperOnDemand>
            <alwaysSuppress>1</alwaysSuppress>
            <enableSpeech>0</enableSpeech>
            <whisperSetup>phoneToScreen</whisperSetup>
        </protectParams>
    </Scenario_STORES_EUR_OUTBOUND>
</config>
EOD;
$result = [];
$xml = new SimpleXMLElement($xmlString);
$syndications = file_get_contents('LA-Syndications.xml');
foreach ($xml as $syndicName => $syndic) {
    $syndications = str_replace("changeMe$syndicName", $syndic->protectParams->destination."", $syndications);
}
var_dump($syndications);

